### ISSUE TITLE
nilpointer when adding new collector

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#246]
just saw this in devstack.
launched a devstack. for some reason it was missing a collector, but then i added a new collector, and then this happened:

```
2015/06/24 08:22:49 http: response.WriteHeader on hijacked connection
2015/06/24 08:22:49 ESC[1;32m[I] collector with version 0.1.100000 connectedESC[0m
2015/06/24 08:22:49 ESC[1;32m[I] collector with version 0.1.100000 connectedESC[0m
2015/06/24 08:22:49 http: response.WriteHeader on hijacked connection
2015/06/24 08:22:49 ESC[1;32m[I] Completed /socket.io/ 400 Bad Request in 751.724<C2><B5>sESC[0m
2015/06/24 08:22:49 ESC[1;32m[I] Completed /socket.io/ 400 Bad Request in 989.354<C2><B5>sESC[0m
2015/06/24 08:22:49 ESC[1;32m[I] processing amqp message with routing key: INFO.collector.connectedESC[0m
2015/06/24 08:22:49 ESC[1;32m[I] Collector 2 refreshingESC[0m
searching for sessions for collector 2
2015/06/24 08:22:49 ESC[1;32m[I] New connection for dietertest owned by OrgId: 1ESC[0m
2015/06/24 08:22:49 ESC[1;32m[I] sending refresh to 16MqjAkYs63rZDc3w9LTESC[0m
2015/06/24 08:22:49 ESC[1;31m[log.go:198 writerMsg()] [E] Failed to initialize collector.%!(EXTRA *mysql.MySQLError=Error 1062: Duplicate entry '1-dietertest' for key 'UQE_collector_org_id_
slug')ESC[0m
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x76036d]

goroutine 62 [running]:
github.com/googollee/go-socket%2eio.(*decoder).Close(0x0)
        /go/src/github.com/googollee/go-socket.io/parser.go:161 +0x7d
github.com/googollee/go-socket%2eio.(*socketHandler).onPacket(0xc2088fffa0, 0x0, 0xc2083f9840, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/googollee/go-socket.io/handler.go:146 +0x11f
github.com/googollee/go-socket%2eio.func<C2><B7>004()
        /go/src/github.com/googollee/go-socket.io/socket.go:117 +0xb8
github.com/googollee/go-socket%2eio.(*decoder).Close(0xc2083f9700)
        /go/src/github.com/googollee/go-socket.io/parser.go:161 +0x3b
github.com/googollee/go-socket%2eio.(*socketHandler).onPacket(0xc2088fffa0, 0xc2083f9700, 0xc2083f9740, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/googollee/go-socket.io/handler.go:146 +0x11f
github.com/googollee/go-socket%2eio.(*socket).loop(0xc2083b7e60, 0x0, 0x0)
        /go/src/github.com/googollee/go-socket.io/socket.go:135 +0x37b
github.com/googollee/go-socket%2eio.func<C2><B7>003(0xc2083b7e60)
        /go/src/github.com/googollee/go-socket.io/server.go:93 +0x28
created by github.com/googollee/go-socket%2eio.(*Server).loop
        /go/src/github.com/googollee/go-socket.io/server.go:94 +0x109

```

**Comment by whisk3y** [comment]
I am also getting this error. I compiled raintank/grafana and raintank-collector locally. I am running with just one graphite server which I have configured grafana to use before I compiled.

```
[raintank]
graphite_url = http://localhost:8080/
```
Collector ./etc/config.js:
```
{
        "collector": {
                "name": "collector1"
        },
        "numCPUs": 1,
        "serverUrl": "http://localhost:3000",
        "apiKey": "<MYKEY>",
        "pingServerPort": 8081
}
```
config.js:
```
'use strict;'
var nopt = require('nopt');
var path = require('path');

var parsedOpts = nopt({"config": path}, {"c": ["--config"]}, process.argv, 2)
var config;

if (parsedOpts["config"]) {
  config = require(parsedOpts['config']);
} else {
  config = require('./etc/config.json');
}

config.probeServerPort = parseInt(config.probeServerPort) || 8081

function parseEnv(name, value, cnf) {
        if (name in cnf) {
                cnf[name] = value;
                return;
        }
        var parts = name.split('_');
        var pos = 0
        var found = false
        while (!found && pos < parts.length) {
                pos = pos + 1;
                var group = parts.slice(0,pos).join('_');
                if (group in cnf){
                        found = true;
                        parseEnv(parts.slice(pos).join('_'), value, cnf[group]);
                }
        }
        if (!found) {
                console.log("%s not found in config", name);
        }
}

// overwrite with Environment variables
for (var key in process.env) {
        if (key.indexOf('RAINTANK_') == 0) {
                var name = key.slice(9);
                parseEnv(name, process.env[key], config);
        }
}

exports.config = config;
```


Panic from grafana:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x576bf3]

goroutine 30 [running]:
github.com/grafana/grafana/pkg/services/metricpublisher.Publish(0xc208536720, 0x3, 0x4, 0x0, 0x0)
	/home/dustin/gocode/src/github.com/grafana/grafana/pkg/services/metricpublisher/metricpublisher.go:95 +0x303
github.com/grafana/grafana/pkg/api.(*CollectorContext).OnResults(0xc2084839e0, 0xc208536720, 0x3, 0x4)
	/home/dustin/gocode/src/github.com/grafana/grafana/pkg/api/socketio.go:374 +0x9c
github.com/grafana/grafana/pkg/api.*CollectorContext.OnResults·fm(0xc208536720, 0x3, 0x4)
	/home/dustin/gocode/src/github.com/grafana/grafana/pkg/api/socketio.go:281 +0x45
reflect.Value.call(0xc3d2a0, 0xc20828cf40, 0x13, 0xf1ab10, 0x4, 0xc2085368a0, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/lib/golang/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xc3d2a0, 0xc20828cf40, 0x13, 0xc2085368a0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/reflect/value.go:296 +0xbc
github.com/googollee/go-socket%2eio.(*caller).Call(0xc208487a00, 0x7f75a882a738, 0xc20815a330, 0xc208075800, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/dustin/gocode/src/github.com/googollee/go-socket.io/caller.go:75 +0x3e8
github.com/googollee/go-socket%2eio.(*socketHandler).onPacket(0xc2084765e0, 0xc208487b80, 0xc208487bc0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/dustin/gocode/src/github.com/googollee/go-socket.io/handler.go:158 +0x410
github.com/googollee/go-socket%2eio.(*socket).loop(0xc20815a330, 0x0, 0x0)
	/home/dustin/gocode/src/github.com/googollee/go-socket.io/socket.go:125 +0x37b
github.com/googollee/go-socket%2eio.func·003(0xc20815a330)
	/home/dustin/gocode/src/github.com/googollee/go-socket.io/server.go:93 +0x28
created by github.com/googollee/go-socket%2eio.(*Server).loop
	/home/dustin/gocode/src/github.com/googollee/go-socket.io/server.go:94 +0x109

goroutine 1 [IO wait, 1 minutes]:
net.(*pollDesc).Wait(0xc20847b560, 0x72, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20847b560, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20847b500, 0x0, 0x7f75a8817ef0, 0xc2081a9a30)
	/usr/lib/golang/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208437078, 0x6502de, 0x0, 0x0)
	/usr/lib/golang/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc208437078, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc208445f20, 0x7f75a8829f40, 0xc208437078, 0x0, 0x0)
	/usr/lib/golang/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc208445f20, 0x0, 0x0)
	/usr/lib/golang/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc208281270, 0xc, 0x7f75a8829e38, 0xc2083819d0, 0x0, 0x0)
	/usr/lib/golang/src/net/http/server.go:1808 +0xba
github.com/grafana/grafana/pkg/cmd.StartServer()
	/home/dustin/gocode/src/github.com/grafana/grafana/pkg/cmd/web.go:94 +0x3e1
main.main()
	/home/dustin/gocode/src/github.com/grafana/grafana/main.go:100 +0x5f3
```

**Comment by dahendel** [comment]
Correction. I can add a collector, when it tries to write it blows up.

**Comment by ctdk** [comment]
@dahendel Do you know which version or git hash of grafana you're having this problem with?

**Comment by ctdk** [comment]
@dahendel @Dieterbe I've been trying to duplicate this, but with no luck so far. Still at it.

**Comment by woodsaj** [comment]
There are two separate issues here.

1). 
```
2015/06/24 08:22:49 ESC[1;31m[log.go:198 writerMsg()] [E] Failed to initialize collector.%!(EXTRA *mysql.MySQLError=Error 1062: Duplicate entry '1-dietertest' for key 'UQE_collector_org_id_
slug')
```

this is due to a collector being configured with numCPUs greater then 1.  This results in multiple concurrent connections to the grafana server which are being processed concurrently.  Due to a race condition, only one of the connections succeeds in connecting and the other will fail fail due to the duplicate entry in the DB.  We need to catch this failure and handle it more gracefully.

2).
```
github.com/grafana/grafana/pkg/services/metricpublisher.Publish(0xc208536720, 0x3, 0x4, 0x0, 0x0)
    /home/dustin/gocode/src/github.com/grafana/grafana/pkg/services/metricpublisher/metricpublisher.go:95 +0x303
```
Here, grafana is trying to publish metrics but metric_publishing is disabled.  We need to check that the globalProducer is defined before trying push metrics to it at https://github.com/raintank/grafana/blob/master/pkg/services/metricpublisher/metricpublisher.go#L72

**Comment by Dieterbe** [comment]
i'll take care of number 2

**Comment by woodsaj** [comment]
This were both resolved.
