### ISSUE TITLE
grafana-server crashing: Error 1213: Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by woodsaj** [raintank/grafana#290]
I updated the init script on one of the prod servers to capture stderr.  captured this when it crashed.

panic: failed to update monitor state. Error 1213: Deadlock found when trying to get lock; try restarting transaction
goroutine 87 [running]:
github.com/grafana/grafana/pkg/alerting.Executor(0x10709f8, 0xc20c6ca660, 0xc20c57ab80)
        /opt/go/src/github.com/grafana/grafana/pkg/alerting/executor.go:114 +0xced
created by github.com/grafana/grafana/pkg/alerting.distributed
        /opt/go/src/github.com/grafana/grafana/pkg/alerting/init.go:187 +0x629

**Comment by woodsaj** [comment]
https://github.com/raintank/grafana/commit/214fc22f4ffe48fd89b6ce78ce90e2c3aba59d71 will prevent the server from crashing when the deadlock is encountered. 

but we still need to identify why the deadlock is happening.

**Comment by woodsaj** [comment]
Given that the query that is generating the deadlock is a single update using the primary key, the deadlock must be getting generated due to Galera's optimistic locking.

This article explains the issue pretty well.
http://www.severalnines.com/blog/avoiding-deadlocks-galera-set-haproxy-single-node-writes-and-multi-node-reads

So this is not really a problem with the code, but rather just a drawback of using Galera clustering with Mysql/Mariadb.  The changes proposed in https://github.com/raintank/ops/issues/28 should alleviate this problem in production as the grafana-server in each zone will preference the MariaDB node in the same zone.  As alerting jobs are routed via consistent hashing, updates for the same row in the DB will be executed on the one mariadb node.

However, deadlocks happen for a large number of reasons and are not necessarily due to a fault.  We should  retry transactions at least once when encountering deadlock issues rather then just giving up and raising an error.
