### ISSUE TITLE
alert emails not being sent.

### ISSUE THREAD

**Issue by woodsaj** [raintank/grafana#455]
```
2015/09/07 15:13:32 ESC[1;32m[I] sending email. addr=anthony@monkey.id.au, orgId=2, monitorId=646, endpointSlug=mon
key_id_au, state=CriticalESC[0m
panic: interface conversion: interface is nil, not string
goroutine 197 [running]:
github.com/grafana/grafana/pkg/services/notifications.sendEmailCommandHandler(0xc2081b19f0, 0x0, 0x0)
        /home/ubuntu/.go_workspace/src/github.com/grafana/grafana/pkg/services/notifications/notifications.go:75 +0
x354
reflect.Value.call(0xc341e0, 0x1108458, 0x13, 0xecd8b0, 0x4, 0xc209bc1650, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xc341e0, 0x1108458, 0x13, 0xc209bc1650, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:296 +0xbc
github.com/grafana/grafana/pkg/bus.(*InProcBus).Dispatch(0xc20803d7d0, 0xbb0b60, 0xc2081b19f0, 0x0, 0x0)
        /home/ubuntu/.go_workspace/src/github.com/grafana/grafana/pkg/bus/bus.go:48 +0x38d
github.com/grafana/grafana/pkg/bus.Dispatch(0xbb0b60, 0xc2081b19f0, 0x0, 0x0)
        /home/ubuntu/.go_workspace/src/github.com/grafana/grafana/pkg/bus/bus.go:118 +0x58
github.com/grafana/grafana/pkg/alerting.execute(0x1108020, 0xc208902e00, 0xc2083b1f00, 0x0, 0x0)
        /home/ubuntu/.go_workspace/src/github.com/grafana/grafana/pkg/alerting/executor.go:238 +0x2704
github.com/grafana/grafana/pkg/alerting.func·002(0xc208582f00, 0x0, 0x0)
        /home/ubuntu/.go_workspace/src/github.com/grafana/grafana/pkg/alerting/executor.go:78 +0x5b7
github.com/grafana/grafana/pkg/services/rabbitmq.func·002()
        /home/ubuntu/.go_workspace/src/github.com/grafana/grafana/pkg/services/rabbitmq/consumer.go:148 +0x10d
created by github.com/grafana/grafana/pkg/services/rabbitmq.(*Consumer).consume
        /home/ubuntu/.go_workspace/src/github.com/grafana/grafana/pkg/services/rabbitmq/consumer.go:155 +0x205

```

**Comment by woodsaj** [comment]
This was due to the grafana conf having the wrong templates dir set, so the SendEmailCommandHandler  couldnt fins the alert_emails template.

Opened https://github.com/grafana/grafana/issues/2690 to improve the error handling here so that we dont end up with a panic
