### ISSUE TITLE
email sending: panic: interface conversion: interface is nil, not string

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#467]
this happens when trying to send an alert notification
```
panic: interface conversion: interface is nil, not string

goroutine 76 [running]:
github.com/grafana/grafana/pkg/services/notifications.sendEmailCommandHandler(0xc20840d0e0, 0x0, 0x0)
        /go/src/github.com/grafana/grafana/pkg/services/notifications/notifications.go:75 +0x354
reflect.Value.call(0xc78e40, 0x116a808, 0x13, 0xf23270, 0x4, 0xc2086eb658, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xc78e40, 0x116a808, 0x13, 0xc2086eb658, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:296 +0xbc
github.com/grafana/grafana/pkg/bus.(*InProcBus).Dispatch(0xc20803d800, 0xbf4200, 0xc20840d0e0, 0x0, 0x0)
        /go/src/github.com/grafana/grafana/pkg/bus/bus.go:48 +0x38d
github.com/grafana/grafana/pkg/bus.Dispatch(0xbf4200, 0xc20840d0e0, 0x0, 0x0)
        /go/src/github.com/grafana/grafana/pkg/bus/bus.go:118 +0x58
github.com/grafana/grafana/pkg/alerting.execute(0x116a3f0, 0xc208531b00, 0xc20815c680, 0x0, 0x0)
        /go/src/github.com/grafana/grafana/pkg/alerting/executor.go:236 +0x2511
github.com/grafana/grafana/pkg/alerting.func·002(0xc208062140, 0x0, 0x0)
        /go/src/github.com/grafana/grafana/pkg/alerting/executor.go:76 +0x595
github.com/grafana/grafana/pkg/services/rabbitmq.func·002()
        /go/src/github.com/grafana/grafana/pkg/services/rabbitmq/consumer.go:148 +0x10d
created by github.com/grafana/grafana/pkg/services/rabbitmq.(*Consumer).consume
        /go/src/github.com/grafana/grafana/pkg/services/rabbitmq/consumer.go:155 +0x205
```

```
+  75   log.Info("%q", data)
+  76 # the line below used to be line 75, throwing the error
   77   subjectTmplText := data["Subject"].(map[string]interface{})["value"].(string)
   78   subjectTmpl, err := template.New("subject").Parse(subjectTmplText)
   79   if err != nil {
   80     return err
   81   }
```

the log.Info call shows:
```
2015/09/15 11:42:31 [I] map["EndpointName":"dns.be" "EndpointSlug":"dns_be" "BuildStamp":'\x00' "EndpointId":'\x01' "Settings":map["port":"80" "expectRegex":"" "headers":"Accept-Encoding: gzip\nUser-Agent: raintank collector\n" "host":"www.dnsbelgium.be" "method":"GET" "path":"/"] "CheckType":"HTTP" "State":"OK" "TimeLastData":"2015-09-15 11:42:01 +0000 UTC" "TimeExec":"2015-09-15 11:42:31.002562228 +0000 UTC" "AppUrl":"http://localhost:80/" "BuildVersion":"master" "EmailCodeValidHours":'\x02' "Subject":map[]]
```

**Comment by woodsaj** [comment]
This is a known issue when the template being requested cant be found or is not valid.

It has already been fixed upstream
https://github.com/grafana/grafana/issues/2690
